### ISSUE TITLE
Installing python3 libraries fails

### ISSUE THREAD

**Issue by jupstra** [FilipDem/Domoticz-NEST-plugin#13]
Hello
Thanks for making this workaround. When trying to install the python3 libraries <json> and <time> on my RPI3B they fail though:

- json: Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/json/
- time: Could not find a version that satisfies the requirement time (from versions: )
No matching distribution found for time

Hope you can help!

**Comment by FilipDem** [comment]
I made a copy/paste error and json and time libraries are standard
available and should not be installed.
So probably the plugin is working as such (you can see in the Domoticz log
if there would be an error generated).
I also found another error... To check the availability, it is not pip3
<library>, but pip3 list.
Sorry for this (were last minute changes and I did it too fast).
Could you confirm that it is working to close the topic then? I will update
the installation instructions.
Filip

Op di 27 okt. 2020 om 23:28 schreef jupstra <notifications@github.com>:

**Comment by jupstra** [comment]
It works, awesome! For the installation instructions it might help to add that people need to restart the domoticz service `sudo systemctl restart domoticz.service` in order to have the plugin working.
Further in the configuration settings, it might help to add a few instructions on how to add the new hardware in Domoticz (what names to look for). Not everyone might be that familiar with Domoticz plugins. Finally I noticed that renaming the devices, results in creating new devices with the old names, disconnecting the old ones. No biggy, but maybe to warn people for. Keep up the good work!

**Comment by FilipDem** [comment]
Thanks for the feedback and it is integrated in the text.
