### ISSUE TITLE
Dining Room Heating Temp does not generate temperature graph in domoticz

### ISSUE THREAD

**Issue by kitopopo** [FilipDem/Domoticz-NEST-plugin#15]
Dear @FilipDem 

First of all I thank you for this magnificent plugin. Congratulations.

Dining Room Heating Temp (within utilities) does the temperature graph generate in domoticz? I have an empty temperature graph, it does not generate any data, I am not sure but I would say that a couple of weeks ago it generated this graph, do you know why it is due or how can I solve it? 

In my case, the temperature varies correctly according to the temperature of the room, but the graph is not shown any data and it would be quite useful. Thanks in advance

**Comment by FilipDem** [comment]
In my case the graph is correctly shown... See screenshot. Or am I misunderstanding your question?
![Screenshot from 2020-11-06 16-11-42](https://user-images.githubusercontent.com/16196363/98382016-eebd8a80-204a-11eb-8762-f4a48329030a.png)

**Comment by kitopopo** [comment]
thanks for your reply. It's funny, it comes out blank for me. I'll try to reinstall the plugin, I don't understand why it doesn't show me the graphics. I have cleared the browser cache and this is not the problem. a cordial greeting

![temp](https://user-images.githubusercontent.com/51416982/98401499-153cef00-2066-11eb-9c7e-c23167e416f2.jpg)
