### ISSUE TITLE
Is it possible to update the thermostat information in seconds instead of minutes?

### ISSUE THREAD

**Issue by kitopopo** [FilipDem/Domoticz-NEST-plugin#17]
Hello dear friend, 

thanks for your plugin, it works really well.

In the plugin configuration we can update nest using minutes (Minutes between update). Would it be possible to modify the plugin so that the update frequency was fixed per seconds? I would like to be able to set the update refresh to a shorter time, I do not know if it is possible. I have tried 0.5 minutes but it doesn't work. Thanks in advance.

**Comment by FilipDem** [comment]
This should be possible. To remain compatible I will need to use indeed
fractions... Will look to make this working...
I would not recommend to go lower than 30 sec seen the communication with
the nest servers take from time to time a bit of time...
I keep you posted about the progress.
Filip

Op vr 25 dec. 2020 19:41 schreef kitopopo <notifications@github.com>:

**Comment by kitopopo** [comment]
Thanks @FilipDem . Mery christmas. Best regards

**Comment by FilipDem** [comment]
Update done. Now it is possible to use fractions in "Minutes between update". So for an update every 30 seconds, enter 0.5; for every 20 seconds, enter 0.33. Personally I am not convinced that the update interval should be lower than 1 minute... However the plugin now supports it. 
@kitopopo, small donations are always welcome if you judge the plugin valuable and the service good. Just click the donation button and follow the instructions. Thanks in advance.

**Comment by kitopopo** [comment]
Thanks very much

**Comment by FilipDem** [comment]
New feature
