### ISSUE TITLE
Temperature deviation 0,2 degrees Celsius 

### ISSUE THREAD

**Issue by erwindw87** [FilipDem/Domoticz-NEST-plugin#21]
Hello,

Thank you for your effort and building this great work-around. 
Just a question; in domoticz there is a deviation in the temperature by 0,2 degrees. When the Nest measures a temperature of 21 degrees, Domoticz shows 21,2 degrees. When i set the temperature at 20,5 degrees on the nest, Domoticz says a set-temperature of 20,7 degrees.
Is there a way to correct this?

thank you in advance 
Erwin

**Comment by erwindw87** [comment]
![Uploading B2A4750B-EF39-472C-BC0C-38E00C891CE1.jpeg…]()

**Comment by FilipDem** [comment]
Hi Erwin,
I will take a look at it during the weekend... My assumption is rather that the Nest thermostat rounds the value to a 0.5 degree. I am (normally) showing what is coming back from the Nest server. I will check this weekend to be 100% sure. If it would be correct I see 2 possibilities:
- Leave it as now
- Round also the value to 0.5 degrees (so it is aligned with Nest)

Btw: thank you for the contribution.

Filip

**Comment by erwindw87** [comment]
Hi Filip,

You're welcome, thank you for your fast respons. 

It looks like you're right, Nest round the temperature value to a 0,5°.

Don't bother, this works fine enough for me as it is. I thought the deviation in Domoticz was always the same (+ 0,2°C) but I can now see it varies. 

Last night Nest measures 20°C, Domoticz shows 20.2°C (deviation of +0,2°)
Between 05:00 and 05:30 Nest measures 20°C, Domoticz shows 20.3°C (deviation of +0,3°)
At this moment, the temperature is 21°C according to Nest, Domoticz shows 20.9°C (deviation of -0,1°)

If there is a simple way to round all temperatures in Domoticz to 0,5° at once in a simple way, that will be great. If not, that's no problem, I can round them up in my head :). 

Thanks
Erwin 
![afbeelding](https://user-images.githubusercontent.com/80293656/110441631-47189d80-80ba-11eb-80ee-786af50c56af.png)

**Comment by FilipDem** [comment]
Hi Erwin,
I have made an update...
I have made the option to round to the nearest 0.5 degrees optional with a configuration file. With this solution, I don't impact people already using the plugin.
Update the plugin.py and the nest.py (!! a change is made concerning the "Away"-device - see the Readme, section Migration). Add also the default configuration file GoogleNest.json in the plugin/GoogleNest directory. If you change in this file the "RoundTemperature" from 0 to 1, the temperature indicated in the "Temp/Hum"-device will be rounded to the nearest 0.5 degrees.
I tested it and it works at my side... Let me know if it also works for you.
Filip

**Comment by erwindw87** [comment]
That sounds great, I will try this tonight. I’ll let you know if it works for me. Thank you

**Comment by erwindw87** [comment]
Hi Filip,
I've updated your files and it looks like it works great! The temperature in Domoticz now is the same as the readings from Nest itself. Thank you so much!! :)
Kind regards,
Erwin

![afbeelding](https://user-images.githubusercontent.com/80293656/110689549-1718e980-81e3-11eb-954d-be42047907ba.png)

**Comment by erwindw87** [comment]
Hi Filip,
I've updated your files and it looks like it works great! The temperature in Domoticz is now the same as the measurements from Nest itself; 20, 20.5 or 21 ° instead of all kinds of intermediate temperatures. Thank you so much!! :)
Kind regards,
Erwin

![afbeelding](https://user-images.githubusercontent.com/80293656/110690472-454af900-81e4-11eb-8f62-3592354d3b81.png)
