### ISSUE TITLE
After update the plugin error lines plugin.py in domoticz

### ISSUE THREAD

**Issue by kitopopo** [FilipDem/Domoticz-NEST-plugin#22]
Dear friend,

I have updated the plugin using git pull in the plugin folder.After update the plugin appears the following error lines in domoticz:

```
2021-03-19 22:34:29.408 Error: Python Plugin System: (NEST GOOGLE) 'onStart' failed 'TypeError':'argument of type 'NoneType' is not iterable'.
2021-03-19 22:34:29.408 Error: Python Plugin System: (NEST GOOGLE) ----> Line 420 in '/home/pi/domoticz/plugins/Domoticz-NEST-plugin/plugin.py', function onStart
2021-03-19 22:34:29.408 Error: Python Plugin System: (NEST GOOGLE) ----> Line 168 in '/home/pi/domoticz/plugins/Domoticz-NEST-plugin/plugin.py', function onStart
```
I have chequed these lines but I can't find anything. I had to go back to the previous version of the plugin ( 26th december ) . This version works correctly. 

Can you solve the problem?

Thanks in advanced.

Best regards

**Comment by FilipDem** [comment]
Be sure you also copied the file GoogleNest.json.
Not very good from my side not having foreseen the situation when the file is not available... But anyway, copying the file should solve your situation.

Read also the paragraph "Migration" in the readme.

Filip

**Comment by kitopopo** [comment]
Dear friend,

In all old versions of plugin the GoogleNest.josn doesn't exist and the plugin works correctly. what is the use of this file? thanks in advanced. Best regards

**Comment by FilipDem** [comment]
Dear, that's why we make sometimes new version.
This version contains a different management of the next Protect devices. There is now even a Away device when only having Best Protect. This was not the case before...
About the JSON file... I got a request to have the Nest temperature in Domoticz aligned with the Nest app. In the Nest app, the degrees are rounded to a 0.5 degree. Because I found this rather a technical customisation, I made the JSON to activate this behaviour. 
The last update contains a change that all works before when the file is absent... Instead of generating an error.
Thanks

**Comment by kitopopo** [comment]
Dear friend, thanks for your answer.

I have the file GoogleNest.json inside plugin folder correctly. 
Anyway I have copied it again but the problem is not solved. I keep getting the error:
```

2021-03-25 01:56:28.047 Error: Python Plugin System: (NEST GOOGLE) 'onStart' failed 'TypeError':'argument of type 'NoneType' is not iterable'.
2021-03-25 01:56:28.048 Error: Python Plugin System: (NEST GOOGLE) ----> Line 420 in '/home/pi/domoticz/plugins/Domoticz-NEST-plugin/plugin.py', function onStart
2021-03-25 01:56:28.048 Error: Python Plugin System: (NEST GOOGLE) ----> Line 168 in '/home/pi/domoticz/plugins/Domoticz-NEST-plugin/plugin.py', function onStart
```
plugin.py line 168 -->  if not config and 'RoundTemperature' in config:
plugin.py line 420: -->  plugin.onStart()

Any solution? 

I will return again with my backup to the previous version of the plugin until we find a solution, thanks in advance, best regards

**Comment by FilipDem** [comment]
Normally if you download the JSON in the same directory it should be solved.
I will take it up this weekend to improve if the JSON file is absent...
F

**Comment by kitopopo** [comment]
Dear friend, 

I have done a git pull and then copying the json file. I have also done a git clone installing all the plugin again, and I have also downloaded the zip file and I have replaced all the files with the new ones and nothing works. for now I am staying in the previous version. We will wait until the weekend for you to solve it. Thanks in advance. a cordial greeting

**Comment by FilipDem** [comment]
Sorry friend (hope your reactions "cordial greeting" are not sarcastic).
My apologise but the change was so obvious that it was not decently tested... However I know that what is not tested does not work... Solved the problem, uploaded on my system (with and without the GoogleNest.JSON) and it works.
Sorry again.
Kr,
Filip

**Comment by kitopopo** [comment]
Dear friend,

My comments aren't sarcastic. Sorry. I like to be respectful with all people. Thanks for your help. I will test the plugin soon. Best regards

**Comment by FilipDem** [comment]
Thanks. Let me know!
Always ready to help and support and hope I don't do any stupid mistake anymore...
F

**Comment by kitopopo** [comment]
Dear friend,

I have updated the plugin with git pull and now works correctly. thanks very much. Best regards
