### ISSUE TITLE
API returned error: No active session found

### ISSUE THREAD

**Issue by kitopopo** [FilipDem/Domoticz-NEST-plugin#26]
Dear friend, 

the plugin for domoticz has worked for me correctly for 2 or 3 months, from today I receive the following error in domoticz

`Error: NEST GOOGLE: (NEST GOOGLE) API returned error: No active session found. `

Do you know if something has changed in the way the plugin works? How could you solve the problem? thanks in advance best regards

**Comment by kitopopo** [comment]
I think that this error is due to i changed my google password today. Sorry. Thanks. Best regards

**Comment by FilipDem** [comment]
Indeed that is the case. Thanks.
