### ISSUE TITLE
Nest Thermostat Google is not showing up after installing

### ISSUE THREAD

**Issue by ghost** [FilipDem/Domoticz-NEST-plugin#30]
Followed instructions, added the contents of Github URL into GoogleNest in plugins directory, restarted Domoticz but doesn't appear in Hardware list.

All I see are the original Nest Thermostat and Nest Thermostat OAuth options.

Domoticz v2021.1

**Comment by FilipDem** [comment]
Did you restart the Domoticz service? Or the complete system?
I didn't mention this because this is the basic of adding any plugin.
If this is really the case, perhaps I need to add it...

**Comment by ghost** [comment]
I restarted the service, but didn't reboot the Pi.

I will try rebooting the Pi, and will enable discovery of new devices before I try adding it again though.

**Comment by ghost** [comment]
Still not showing up int he dropdown list.

Also when I tried your pip commands, it kept saying command not found... this could be why? But I have python 3.9.2 by the way, but every time Domoticz starts I have this in my log:

2021-12-03 20:13:42.589 Status: EventSystem - Python: Failed dynamic library load, install the latest libpython3.x library that is available for your platform.

And ideas what to do with this?

**Comment by ghost** [comment]
Got it showing up after I ran sudo apt-get install -y python3-dev

**Comment by FilipDem** [comment]
Thanks for letting me know and happy it is showing up now.
If finally it works and you are happy with the plugin, small financial contributions are welcome... I am spending quite some time to get this maintained which make a bit of support welcome. It is a free choice of course.
