### ISSUE TITLE
Issue device not recognized

### ISSUE THREAD

**Issue by guihome1122** [FilipDem/Domoticz-NEST-plugin#32]
Hi Filip

thanks for the great work.

See the scrip return.

**I have a Nest thermostat Model E is this device supported?**

Thanks

Got bearer token
Got access token and user id (7504305) and remains valid until 2021-12-14T19:55:19.134Z.
Got user
Status: {
  "updated_buckets": [
    {
      "object_key": "user.7504305",
      "object_revision": 9550,
      "object_timestamp": 1639164744312,
      "value": {
        "name": "Guillaume Gaucher",
        "email": "gaucher.g@gmail.com",
        "profile_image_url": "https://lh3.googleusercontent.com/a/default-user",
        "structures": [
          "structure.2d21bdb0-bf59-11e7-bab1-0e967d55f198"
        ],
        "obsidian_version": "5.67rc6",
        "is_merged_with_gaia": true,
        "short_name": "",
        "structure_memberships": [
          {
            "structure": "structure.2d21bdb0-bf59-11e7-bab1-0e967d55f198",
            "roles": [
              "owner"
            ]
          }
        ],
        "acknowledged_onboarding_screens": [
          "family_account_education_2d21bdb0-bf59-11e7-bab1-0e967d55f198",
          "eco",
          "olive_nevis_reassignment"
        ],
        "merged_with_gaia_at": "2019-10-05T15:45:41.000Z"
      }
    },
    {
      "object_key": "where.2d21bdb0-bf59-11e7-bab1-0e967d55f198",
      "object_revision": -779,
      "object_timestamp": 1565622774004,
      "value": {
        "wheres": [
          {
            "where_id": "00000000-0000-0000-0000-00010000000c",
            "name": "Living Room"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000005",
            "name": "Master Bedroom"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000013",
            "name": "Front Yard"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000001",
            "name": "Basement"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000010",
            "name": "Dining Room"
          },
          {
            "where_id": "00000000-0000-0000-0000-00010000001d",
            "name": "Back Door"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000017",
            "name": "Deck"
          },
          {
            "where_id": "00000000-0000-0000-0000-00010000000b",
            "name": "Family Room"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000002",
            "name": "Hallway"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000006",
            "name": "Downstairs"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000012",
            "name": "Driveway"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000009",
            "name": "Bathroom"
          },
          {
            "where_id": "00000000-0000-0000-0000-00010000001c",
            "name": "Side Door"
          },
          {
            "where_id": "00000000-0000-0000-0000-00010000000f",
            "name": "Upstairs"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000016",
            "name": "Shed"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000007",
            "name": "Garage"
          },
          {
            "where_id": "00000000-0000-0000-0000-00010000000a",
            "name": "Kitchen"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000011",
            "name": "Backyard"
          },
          {
            "where_id": "00000000-0000-0000-0000-00010000001b",
            "name": "Front Door"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000015",
            "name": "Guest House"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000003",
            "name": "Den"
          },
          {
            "where_id": "00000000-0000-0000-0000-00010000000e",
            "name": "Office"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000004",
            "name": "Attic"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000014",
            "name": "Outside"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000000",
            "name": "Entryway"
          },
          {
            "where_id": "00000000-0000-0000-0000-00010000000d",
            "name": "Bedroom"
          },
          {
            "where_id": "00000000-0000-0000-0000-000100000018",
            "name": "Patio"
          },
          {
            "where_id": "00000000-0000-0000-0000-00010000001a",
            "name": "Guest Room"
          }
        ]
      }
    },
    {
      "object_key": "structure.2d21bdb0-bf59-11e7-bab1-0e967d55f198",
      "object_revision": 7649,
      "object_timestamp": 1639487837511,
      "value": {
        "swarm": [],
        "last_action_by": "PHX",
        "manual_away_timestamp": 1549052473,
        "last_action": "RTS_SYNC",
        "geofence_enhanced_autoaway": {
          "enabled": false,
          "is_set": true
        },
        "name": "Maison",
        "eta_preconditioning_active": false,
        "creation_time": 1509577538829,
        "location": "Champlain, QC",
        "touched_by": {
          "touched_by": 1,
          "touched_id": "",
          "touched_user_id": ""
        },
        "away_timestamp": 1639487837,
        "topaz_hush_key": "0OFsM76fA6iyZlV7sycXSQ==",
        "enable_goose": false,
        "away_setter": 1,
        "phone_hush_enable": true,
        "hvac_safety_shutoff_enabled": true,
        "house_type": "family",
        "demand_charge_enabled": true,
        "rcs_sensor_swarm": [],
        "aux_primary_fabric_id": "3012124CB2244ABC",
        "topaz_enhanced_auto_away_enabled": false,
        "country_code": "CA",
        "hvac_smoke_safety_shutoff_enabled": false,
        "topaz_away": false,
        "tou_enabled": true,
        "renovation_date": "unknown",
        "vacation_mode": false,
        "fabric_ids": [],
        "postal_code": "G0X1C0",
        "num_thermostats": "unknown",
        "entitlements": {},
        "dr_reminder_enabled": true,
        "members": [
          {
            "user": "user.25320713",
            "roles": [
              "member"
            ]
          },
          {
            "user": "user.7504305",
            "roles": [
              "owner"
            ]
          }
        ],
        "manual_eco_all": false,
        "goose_sensor_events_enabled": true,
        "campaign_id": "8b1621c4-b339-4d83-8268-de57d9e30db9",
        "time_zone": "America/Toronto",
        "user": "user.7504305",
        "clutches": [],
        "away": true,
        "devices": []
      }
    },
    {
      "object_key": "buckets.7504305",
      "object_revision": 28053,
      "object_timestamp": 1639485308781,
      "value": {
        "buckets": [
          "structure.2d21bdb0-bf59-11e7-bab1-0e967d55f198",
          "where.2d21bdb0-bf59-11e7-bab1-0e967d55f198",
          "utility.2d21bdb0-bf59-11e7-bab1-0e967d55f198",
          "structure_history.2d21bdb0-bf59-11e7-bab1-0e967d55f198",
          "trip.2d21bdb0-bf59-11e7-bab1-0e967d55f198",
          "wwn_security.2d21bdb0-bf59-11e7-bab1-0e967d55f198",
          "user.7504305",
          "user_alert_dialog.7504305",
          "message_center.7504305",
          "user_settings.7504305",
          "buckets.7504305",
          "structure_metadata.2d21bdb0-bf59-11e7-bab1-0e967d55f198",
          "safety.2d21bdb0-bf59-11e7-bab1-0e967d55f198",
          "safety_summary.2d21bdb0-bf59-11e7-bab1-0e967d55f198",
          "geofence_info.2d21bdb0-bf59-11e7-bab1-0e967d55f198",
          "partner_programs.2d21bdb0-bf59-11e7-bab1-0e967d55f198"
        ]
      }
    }
  ],
  "service_urls": {
    "urls": {
      "rubyapi_url": "https://home.nest.com/",
      "czfe_url": "https://czfe12-front01-iad01.transport.home.nest.com",
      "log_upload_url": "https://logsink.home.nest.com/upload/user",
      "transport_url": "https://czfe12-front01-iad01.transport.home.nest.com",
      "weather_url": "https://apps-weather.nest.com/weather/v1?query=",
      "support_url": "https://nest.secure.force.com/support/webapp?",
      "direct_transport_url": "https://transport01-rts26-iad01.transport.home.nest.com:443"
    },
    "limits": {
      "thermostats_per_structure": 20,
      "structures": 5,
      "smoke_detectors_per_structure": 18,
      "smoke_detectors": 54,
      "thermostats": 60
    },
    "weave": {
    }
  },
  "weather_for_structures": {
    "structure.2d21bdb0-bf59-11e7-bab1-0e967d55f198": {
      "current": {
        "icon": "sunny",
        "temp_c": "-0.6",
        "sunrise": "1639484700",
        "sunset": "1639515780"
      },
      "location": {
        "city": "Champlain",
        "state": "QC",
        "zip": "G0X1C0",
        "country": "CA"
      }
    }
  },
  "2fa_enabled": true
}
Got nest devices 0: thermostats [] - protects []
General Nest information: {'Name': 'Maison', 'Away': True}
All good

**Comment by FilipDem** [comment]
Probably it is indeed your model E...
I can however not debug as I don't have access to such a model E.
If you would debug, I am always willing to put the changes back in the public source.
Kr,
F

**Comment by FilipDem** [comment]
Sorry... Did a bit of research... It was a long time I worked on this topic... In my readme it is clearly mentioned that the model E is excluded (I forgot it :-)). Looking back on the internet, I could only find that the model E is indeed excluded from the several APIs. I didn't found a solution...
Kr,

**Comment by guihome1122** [comment]
Thanks for your hard work anyway.

Have a nice day

Guillaume

**Comment by herbertblom** [comment]
Dear FilipDem,
I tride the plugin but didn't work for me, but i can not remove it from domoticz hardware. Domoticz is hanging and won't do a thing. Restart domoticz with no result. It is on a raspberry pi.
Do you have any idea how i can remove the plugin from the hardware chapter of domoticz?

Greetings,
Herbert Blom

**Comment by FilipDem** [comment]
Mmmm. I don't have really an idea... Nee sure that the files are still in the plug-in directory. Then try first to stop/disable the plug-in and then remove it.
I already saw in the past some topics in the forum how to remove a hardware that sells to have problems removing from the GUI.
I cannot really see what is going wrong as I don't have the problem myself.
F

**Comment by herbertblom** [comment]
Filip,
i cant get it to stop/disable so it will stay in hardware untill someone knows how to.
Best wishes.

Herbert

**Comment by FilipDem** [comment]
It just kept me busy thinking about the possible cause...
I could imagine something went wrong with stopping the thread. So I added a timeout on the onStop event. It will try to stop all the threads. However if it is not possible to stop, the plugin will anyway stop, but possibly crash (as there is still a thread running - see domoticz plugin documentation).
Hope this could help.

**Comment by herbertblom** [comment]
Filip

I stopped and deleted the hardware in domoticz. 
I changed the password at the login at google and that did the thing for me. 
There was no other way. 
Sorry for your worrying about it. 
I hope it did not keep you awake at night. 

Met vriendelijke groet,
Herbert Blom
