### ISSUE TITLE
KeyError: 'Away' 

### ISSUE THREAD

**Issue by ganq76** [FilipDem/Domoticz-NEST-plugin#37]
When I start  python3 nest.py

I don't have Away feature, so the prog failed : 

Nest Thermostat XXXXXXXXXXX: 
{'Target_temperature': 16.01007, 
'Current_temperature': 18.21999, 
'Temperature_scale': 'C', 
'Humidity': 63, 'Eco': False,
 'Heating': False, 'Target_mode':
 'heat', 'Target_temperature_low': 20.0, 
 'Target_temperature_high': 24.0, 
 'Where': 'Bedroom', 
 'Auto_away': -1}
 
Temperature set to 16.01007
    Set Temperature: True
Traceback (most recent call last):
  File "nest.py", line 493, in <module>
    log("    Set Away: {}".format(thermostat.SetAway(device, infoNest['Away'])))
KeyError: 'Away'

Is it a function to active in Nest or is it possible to test if the option exists ? 

Thanks.

**Comment by FilipDem** [comment]
Perhaps linked with your other reported problem about the postal code... I suppose you did not complete all the settings of your NEST...

**Comment by ganq76** [comment]
It's ok ! that was the problem ! Thanks !
