### ISSUE TITLE
General error TaskHandler: 'Postal_code'

### ISSUE THREAD

**Issue by TomMalfrere** [FilipDem/Domoticz-NEST-plugin#40]
Hi,

your Google Nest plugin worked until 22/03/2023 14:30

Today I'm getting: Google Nest thermostaat: > General error TaskHandler: 'Postal_code'

I've read issue #38
My address is filled in on home.nest.com.

Can you help me out please?

in the domoticz.log file I found:
2022-11-22 17:32:05.276  Error: Google Nest thermostaat: ERRORLEVEL=5 Unable to get update data from Nest (last error: None).

**Comment by FilipDem** [comment]
Please run nest.py outside Domoticz and please insert a line to print the `variable ` structure on line 335.
Push then the output in this issue.
F

**Comment by TomMalfrere** [comment]
When trying to run nest.py from a shell I got an error "API returned error: 400"

So, I probably got logged out some way.

I logged in again and got a new issue_token and cookie.

Now it's working again.

Still I don't understand why I didn't get a more descriptive error.
