### ISSUE TITLE
Cannot Change device name

### ISSUE THREAD

**Issue by AdamWeglarz** [FilipDem/Domoticz-NEST-plugin#6]
Hi,

When I change device name script stops recognizing devices and create new ones.
Can you update it that it checks idx of created devices and not the name that name can be changed?

Adam

**Comment by FilipDem** [comment]
Hi,
Can do this but there remains a problem... Now the name tells me which
device it is. Ie temperature, eco, ... I still need this information. But
then I need somewhere a table that keeps the relationship between the
switch and the idx.
And this table must be persistent to be used after a boot.
The only way I see this is keeping a configuration file with the idx and
switch. Every time a device is created I would need to update and
synchronize it in memory. And then I would need a system when I update know
the plugin and create this file based on the existing devices.
But it am not sure this is the "domoticz" way to do.
Any advice?
Filip

Op ma 30 mrt. 2020 16:49 schreef AdamWeglarz <notifications@github.com>:

**Comment by Tezzlicious** [comment]
Why not save the 'real' name in the Description attribute/field of the domoticz device and just look for it on plugin start to match it?

**Comment by markruys** [comment]
I've implemented this feature and will submit a PR after some more testing.
